FROM ubuntu

RUN apt-get update && apt-get install -y curl libzmq3-dev

# ==================== Put your layers here ====================

# Install python 
#   you can change the istallation if you need a specific version, but python is required for jupyterlab
RUN apt-get update && apt-get install -y python3-pip python3-dev



# ==================== End ====================

# ==================== DO NOT CHANGE THE FOLLOWING ====================
# Install JupyterLab
RUN python3 -m pip install --no-cache-dir \
    "jupyterhub==4.*" \
    "jupyter-server==2.*" \
    "jupyterlab==4.*"

# Utente non-root
RUN useradd -m -u 1000 -s /bin/bash jovyan
ENV HOME=/home/jovyan
WORKDIR $HOME

ENV PATH="/opt/venv/bin:/usr/local/bin:${PATH}"

ENV JUPYTERHUB_SINGLEUSER_APP=jupyter_server.serverapp.ServerApp

USER jovyan

CMD ["python3", "-m", "jupyterhub.singleuser"]
